Serializer for device.sua field
InteractiveAdvertisingBureau/openrtb-proto-v2 pull request #29
Opened 2023-05-16 11:52 UTC by denyskravchuk

Added serialization for the field device.sua

2023-05-16 19:35 UTC, dmytro-babichev requested changes
please add a unit test

2023-05-16 19:35 UTC, dmytro-babichev commented on openrtb-core/src/main/java/com/iabtechlab/openrtb/v2/json/OpenRtbJsonWriter.java
> +  public final void writeSua(UserAgent sua, JsonGenerator gen) throws IOException {
I think it's better call it `UserAgent userAgent`. `sua` is the name of the field, and you specified it above

2023-05-16 19:35 UTC, dmytro-babichev commented on openrtb-core/src/main/java/com/iabtechlab/openrtb/v2/json/OpenRtbJsonWriter.java
> +      for (BrandVersion browser : sua.getBrowsersList()) {
same here, the name of a field is written above. here you can use `brandVersion` name

2023-05-16 19:35 UTC, dmytro-babichev commented on openrtb-core/src/main/java/com/iabtechlab/openrtb/v2/json/OpenRtbJsonWriter.java
> +  public final void writePlatform(BrandVersion platform, JsonGenerator gen) throws IOException {
good example. you have two identical methods, but with different names. this should be avoided

2023-05-16 19:35 UTC, dmytro-babichev requested changes
please add a unit test

2023-05-18 17:39 UTC, dmytro-babichev approved these changes

2023-05-18 17:54 UTC, simontrasler approved these changes
Approved.

2023-05-18 17:54 UTC, merged