add json support for SupplyChain and EID/UID objects
InteractiveAdvertisingBureau/openrtb-proto-v2 pull request #40
Opened 2023-07-10 08:46 UTC by vaa25

2023-07-10 16:27 UTC, dmytro-babichev approved these changes

2023-08-26 23:22 UTC, simontrasler commented
Please rebase to the parent `promoted-extensions` -- I fixed the whitespace issue, and note the object model has been changed so please update this code to reflect that.

2023-09-14 16:14 UTC, dmytro-babichev requested changes
add extension processing

2023-09-15 06:29 UTC, vaa25 commented
There are no new extensions added. There is new message added in openrtb-ext.proto. But I found no readers for other messages in openrtb-ext.proto. I believe no reader needed for new message also.

2023-09-15 16:36 UTC, dmytro-babichev approved these changes

2023-11-30 00:00 UTC, merged