Add new `imp.ext.ae` BidRequest field to IAB schema
InteractiveAdvertisingBureau/openrtb-proto-v2 pull request #54
Opened 2023-10-23 11:25 UTC by Symbols-max

[https://magnite.atlassian.net/browse/TX-10234](https://magnite.atlassian.net/browse/TX-10234)

2023-10-24 16:42 UTC, dmytro-babichev requested changes

2023-10-24 16:42 UTC, dmytro-babichev commented on openrtb-core/src/main/protobuf/openrtb-ext.proto
> +  enum Ae {
I recommend to use Google's schema for reference https://developers.google.com/authorized-buyers/rtb/downloads/open-beta/openrtb-adx-proto

2023-10-25 12:17 UTC, dmytro-babichev approved these changes

2023-10-25 16:30 UTC, simontrasler commented on openrtb-core/src/main/protobuf/openrtb-ext.proto
> +  optional AuctionEnvironment ae = 2 [default = SERVER_SIDE_AUCTION];
Integer (or boolean) type only please. The enums can be defined for convenience/reference, though we do not use them directly in the spec.

2023-10-25 18:24 UTC, simontrasler commented on openrtb-core/src/main/protobuf/openrtb-ext.proto
> +  optional int32 ae = 2;
FYI Google is using `[default = 0]`. (Their equivalent is at https://developers.google.com/authorized-buyers/rtb/downloads/openrtb-adx-proto -- note we do not need to use the same index numbers as them in extensions.)

2023-10-31 18:58 UTC, merged